# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.11 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# 'install' program location 
INSTALL ?= install

# Destination root (/ is used if empty) 
DESTDIR ?= 

#  
AR ?= ar

#  
RANLIB ?= ranlib

# C compiler 
CC = gcc

# C++ compiler 
CXX = g++

# Standard flags for CC 
CFLAGS ?= 

# Standard flags for C++ 
CXXFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
PREFIX = /usr
GRESOURCES_CFLAGS = -I../source -c -std=c17 -pipe -O3 \
	-fasynchronous-unwind-tables -fcf-protection=full -fno-common \
	-fnon-call-exceptions -fsplit-stack -fstack-clash-protection \
	-fstack-protector-all -ftrapv `pkg-config gtk+-3.0 --cflags` \
	-D_FORTIFY_SOURCE=2 $(CPPFLAGS) $(CFLAGS)
GRESOURCES_OBJECTS =  \
	gresources_app_resources.o
NEWSREADER_CXXFLAGS = -I../source -std=c++17 -pipe -O2 -ggdb `pkg-config gtk+-3.0 \
	--cflags` `pkg-config webkit2gtk-4.0 --cflags` `pkg-config libxml-2.0 \
	--cflags` `pkg-config gthread-2.0 --cflags` -D_FORTIFY_SOURCE=2 -DNDEBUG \
	-fasynchronous-unwind-tables -fcf-protection=full \
	-fdelete-null-pointer-checks -feliminate-unused-debug-symbols -fexceptions \
	-fno-common -fnon-call-exceptions -fsized-deallocation -fsplit-stack \
	-fstack-clash-protection -fstack-protector-all -fstrict-aliasing -ftrapv \
	-fvisibility=hidden -Werror -Wfatal-errors -pedantic-errors -Wall -Walloca \
	-Walloc-zero -Wcast-align=strict -Wcast-function-type -Wcast-qual \
	-Wcatch-value=3 -Wconversion -Wdate-time -Wdisabled-optimization \
	-Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wextra \
	-Wextra-semi -Wfloat-equal -Wformat=2 -Wformat-overflow=2 \
	-Wformat-signedness -Wformat-truncation=2 -Wlogical-op -Wno-unused-function \
	-Wno-maybe-uninitialized -Wmissing-profile -Wparentheses -Wpedantic \
	-Wplacement-new=2 -Wredundant-decls -Wshadow -Wstack-protector \
	-Wstrict-overflow=5 -Wstringop-overflow=4 -Wstringop-truncation \
	-Wsuggest-final-methods -Wsuggest-final-types -Wsuggest-override \
	-Wtrampolines -Wundef -Wuninitialized -Wunknown-pragmas \
	-Wunused-const-variable=2 -Wunused-macros -Wunused-parameter \
	-Wzero-as-null-pointer-constant $(CPPFLAGS) $(CXXFLAGS)
NEWSREADER_OBJECTS =  \
	newsreader_application.o \
	newsreader_app_win.o \
	newsreader_article_frame.o \
	newsreader_article_header.o \
	newsreader_headlines_frame.o \
	newsreader_rss_manage.o \
	newsreader_rss_article.o \
	newsreader_rss_feed.o \
	newsreader_rss_reader.o \
	newsreader_rss_util.o \
	newsreader_rss_writer.o \
	newsreader_db.o \
	newsreader_feed_download.o \
	newsreader_feed_parse.o

### Conditionally set variables: ###



### Targets: ###

all: bin/libgresources.a bin/newsreader

install: install_newsreader
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/48x48/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/48x48/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/22x22/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/22x22/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/24x24/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/24x24/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/32x32/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/32x32/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/256x256/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/256x256/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/16x16/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/16x16/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/64x64/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/64x64/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/32x32/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/32x32/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/128x128/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/128x128/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/16x16/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/16x16/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/pixmaps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.xpm $(DESTDIR)$(PREFIX)/share/pixmaps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/applications/
	(cd ../desktop ; $(INSTALL) -m 644  newsreader.desktop $(DESTDIR)$(PREFIX)/share/applications/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/metainfo/
	(cd ../desktop ; $(INSTALL) -m 644  newsreader.appdata.xml $(DESTDIR)$(PREFIX)/share/metainfo/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/man/man7/
	(cd ../doc ; $(INSTALL) -m 644  newsreader.7 newsreader.7.gz $(DESTDIR)$(PREFIX)/share/man/man7/)

uninstall: uninstall_newsreader
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/48x48/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/22x22/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/24x24/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/32x32/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/256x256/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/16x16/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/64x64/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/32x32/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/128x128/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/16x16/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/pixmaps/ ; rm -f newsreader.xpm)
	(cd $(DESTDIR)$(PREFIX)/share/applications/ ; rm -f newsreader.desktop)
	(cd $(DESTDIR)$(PREFIX)/share/metainfo/ ; rm -f newsreader.appdata.xml)
	(cd $(DESTDIR)$(PREFIX)/share/man/man7/ ; rm -f newsreader.7 newsreader.7.gz)

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f bin/libgresources.a
	rm -f bin/newsreader

bin: 
	@mkdir -p bin

bin/libgresources.a: $(GRESOURCES_OBJECTS) bin ../source/rss_ui/app_style.css ../source/rss_ui/newsreader.png ../source/rss_ui/app_resources.xml
	rm -f $@
	$(AR) rcu $@ $(GRESOURCES_OBJECTS)
	$(RANLIB) $@

bin/newsreader: $(NEWSREADER_OBJECTS) bin bin/libgresources.a
	$(CXX) -o $@ $(NEWSREADER_OBJECTS)  gresources_app_resources.o -std=c++17 -pipe -O2 -flto -ggdb -flinker-output=pie `pkg-config gtk+-3.0 --libs` `pkg-config sqlite3 --libs` `pkg-config libcurl --libs` `pkg-config webkit2gtk-4.0 --libs` `pkg-config libxml-2.0 --libs` `pkg-config gthread-2.0 --libs` $(LDFLAGS)

install_newsreader: bin/newsreader
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/bin
	install -c bin/newsreader $(DESTDIR)$(PREFIX)/bin

uninstall_newsreader: 
	rm -f $(DESTDIR)$(PREFIX)/bin/newsreader

gresources_app_resources.o: ./../source/rss_ui/app_resources.c
	$(CC) -c -o $@ $(GRESOURCES_CFLAGS) $(CPPDEPS) $<

newsreader_application.o: ./../source/rss_ui/impl/application.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_app_win.o: ./../source/rss_ui/app_win/impl/app_win.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_article_frame.o: ./../source/rss_ui/app_win/impl/article_frame.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_article_header.o: ./../source/rss_ui/app_win/impl/article_header.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_headlines_frame.o: ./../source/rss_ui/app_win/impl/headlines_frame.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_rss_manage.o: ./../source/rss_ui/rss_manage/impl/rss_manage.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_rss_article.o: ./../source/rss_lib/rss/impl/rss_article.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_rss_feed.o: ./../source/rss_lib/rss/impl/rss_feed.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_rss_reader.o: ./../source/rss_lib/rss/impl/rss_reader.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_rss_util.o: ./../source/rss_lib/rss/impl/rss_util.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_rss_writer.o: ./../source/rss_lib/rss/impl/rss_writer.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_db.o: ./../source/rss_lib/db/impl/db.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_feed_download.o: ./../source/rss_lib/rss_download/impl/feed_download.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

newsreader_feed_parse.o: ./../source/rss_lib/rss_parse/impl/feed_parse.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean install_newsreader uninstall_newsreader


# Dependencies tracking:
-include ./*.d
