# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.11 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# 'install' program location 
INSTALL ?= install

# Destination root (/ is used if empty) 
DESTDIR ?= 

#  
AR ?= ar

#  
RANLIB ?= ranlib

# C compiler 
CC = gcc

# C++ compiler 
CXX = g++

# Standard flags for CC 
CFLAGS ?= 

# Standard flags for C++ 
CXXFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
PREFIX = /usr
GRESOURCES_CFLAGS = -I../source -c -std=c17 -pipe -O3 \
	-fasynchronous-unwind-tables -fcf-protection=full -fno-common \
	-fnon-call-exceptions -fstack-protector-all -ftrapv `pkg-config gtk+-3.0 \
	--cflags` -D_FORTIFY_SOURCE=2 $(CPPFLAGS) $(CFLAGS)
GRESOURCES_OBJECTS =  \
	gresources_app_resources.o
NEWSREADER_CLANG_TEST_CXXFLAGS = -I../source -std=c++17 -pipe `pkg-config \
	gtk+-3.0 --cflags` `pkg-config webkit2gtk-4.0 --cflags` `pkg-config libxml-2.0 \
	--cflags` `pkg-config gthread-2.0 --cflags` -Werror -Wfatal-errors \
	-pedantic-errors -Wall -Wextra -Wno-unused-function -Wno-uninitialized \
	$(CPPFLAGS) $(CXXFLAGS)
NEWSREADER_CLANG_TEST_OBJECTS =  \
	newsreader_clang_test_application.o \
	newsreader_clang_test_app_win.o \
	newsreader_clang_test_article_frame.o \
	newsreader_clang_test_article_header.o \
	newsreader_clang_test_headlines_frame.o \
	newsreader_clang_test_rss_manage.o \
	newsreader_clang_test_rss_article.o \
	newsreader_clang_test_rss_feed.o \
	newsreader_clang_test_rss_reader.o \
	newsreader_clang_test_rss_util.o \
	newsreader_clang_test_rss_writer.o \
	newsreader_clang_test_db.o \
	newsreader_clang_test_feed_download.o \
	newsreader_clang_test_feed_parse.o

### Conditionally set variables: ###



### Targets: ###

all: bin/libgresources.a bin/newsreader_clang_test

install: install_newsreader_clang_test
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/48x48/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/48x48/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/22x22/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/22x22/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/24x24/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/24x24/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/32x32/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/32x32/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/256x256/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/256x256/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/HighContrast/16x16/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/HighContrast/16x16/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/64x64/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/64x64/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/32x32/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/32x32/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/128x128/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/128x128/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/16x16/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/16x16/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/pixmaps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  newsreader.xpm $(DESTDIR)$(PREFIX)/share/pixmaps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/applications/
	(cd ../desktop ; $(INSTALL) -m 644  newsreader.desktop $(DESTDIR)$(PREFIX)/share/applications/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/metainfo/
	(cd ../desktop ; $(INSTALL) -m 644  newsreader.appdata.xml $(DESTDIR)$(PREFIX)/share/metainfo/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/man/man7/
	(cd ../doc ; $(INSTALL) -m 644  newsreader.7 newsreader.7.gz $(DESTDIR)$(PREFIX)/share/man/man7/)

uninstall: uninstall_newsreader_clang_test
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/48x48/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/22x22/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/24x24/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/32x32/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/256x256/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/HighContrast/16x16/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/64x64/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/32x32/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/128x128/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/16x16/apps/ ; rm -f newsreader.png)
	(cd $(DESTDIR)$(PREFIX)/share/pixmaps/ ; rm -f newsreader.xpm)
	(cd $(DESTDIR)$(PREFIX)/share/applications/ ; rm -f newsreader.desktop)
	(cd $(DESTDIR)$(PREFIX)/share/metainfo/ ; rm -f newsreader.appdata.xml)
	(cd $(DESTDIR)$(PREFIX)/share/man/man7/ ; rm -f newsreader.7 newsreader.7.gz)

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f bin/libgresources.a
	rm -f bin/newsreader_clang_test

bin: 
	@mkdir -p bin

bin/libgresources.a: $(GRESOURCES_OBJECTS) bin ../source/rss_ui/app_style.css ../source/rss_ui/newsreader.png ../source/rss_ui/app_resources.xml
	rm -f $@
	$(AR) rcu $@ $(GRESOURCES_OBJECTS)
	$(RANLIB) $@

bin/newsreader_clang_test: $(NEWSREADER_CLANG_TEST_OBJECTS) bin bin/libgresources.a
	$(CXX) -o $@ $(NEWSREADER_CLANG_TEST_OBJECTS)  gresources_app_resources.o -std=c++17 -pipe `pkg-config gtk+-3.0 --libs` `pkg-config sqlite3 --libs` `pkg-config libcurl --libs` `pkg-config webkit2gtk-4.0 --libs` `pkg-config libxml-2.0 --libs` `pkg-config gthread-2.0 --libs` $(LDFLAGS)

install_newsreader_clang_test: bin/newsreader_clang_test
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/bin
	install -c bin/newsreader_clang_test $(DESTDIR)$(PREFIX)/bin

uninstall_newsreader_clang_test: 
	rm -f $(DESTDIR)$(PREFIX)/bin/newsreader_clang_test

gresources_app_resources.o: ./../source/rss_ui/app_resources.c
	$(CC) -c -o $@ $(GRESOURCES_CFLAGS) $(CPPDEPS) $<

newsreader_clang_test_application.o: ./../source/rss_ui/impl/application.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_app_win.o: ./../source/rss_ui/app_win/impl/app_win.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_article_frame.o: ./../source/rss_ui/app_win/impl/article_frame.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_article_header.o: ./../source/rss_ui/app_win/impl/article_header.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_headlines_frame.o: ./../source/rss_ui/app_win/impl/headlines_frame.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_rss_manage.o: ./../source/rss_ui/rss_manage/impl/rss_manage.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_rss_article.o: ./../source/rss_lib/rss/impl/rss_article.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_rss_feed.o: ./../source/rss_lib/rss/impl/rss_feed.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_rss_reader.o: ./../source/rss_lib/rss/impl/rss_reader.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_rss_util.o: ./../source/rss_lib/rss/impl/rss_util.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_rss_writer.o: ./../source/rss_lib/rss/impl/rss_writer.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_db.o: ./../source/rss_lib/db/impl/db.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_feed_download.o: ./../source/rss_lib/rss_download/impl/feed_download.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

newsreader_clang_test_feed_parse.o: ./../source/rss_lib/rss_parse/impl/feed_parse.cpp
	$(CXX) -c -o $@ $(NEWSREADER_CLANG_TEST_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean install_newsreader_clang_test \
	uninstall_newsreader_clang_test


# Dependencies tracking:
-include ./*.d
