# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.11 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# 'install' program location 
INSTALL ?= install

# Destination root (/ is used if empty) 
DESTDIR ?= 

#  
AR ?= ar

#  
RANLIB ?= ranlib

# Standard flags for CC 
CFLAGS ?= 

# Standard flags for C++ 
CXXFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
PREFIX = /usr
CC = x86_64-w64-mingw32-gcc
CXX = x86_64-w64-mingw32-g++
GRESOURCES_CFLAGS = -I../source -D_WIN32 -c -std=c17 -pipe -O3 `mingw64-pkg-config \
	gtk+-3.0 --cflags` $(CPPFLAGS) $(CFLAGS)
GRESOURCES_OBJECTS =  \
	gresources_app_resources.o
NEWSREADER_MSWIN_CXXFLAGS = -I../source -std=c++17 -pipe -O2 `mingw64-pkg-config \
	gtk+-3.0 --cflags` `mingw64-pkg-config Qt5WebKit --cflags` \
	`mingw64-pkg-config libxml-2.0 --cflags` `mingw64-pkg-config gthread-2.0 \
	--cflags` -D_WIN32 -DNDEBUG -Werror -Wfatal-errors -pedantic-errors -Wall \
	-Wcast-align -Wcast-qual -Wconversion -Wdate-time -Wdisabled-optimization \
	-Wdouble-promotion -Wextra -Wextra-semi -Wfloat-equal -Wformat=2 \
	-Wno-unused-function -Wno-uninitialized -Wno-parentheses -Wstack-protector \
	-Wstrict-overflow=5 $(CPPFLAGS) $(CXXFLAGS)
NEWSREADER_MSWIN_OBJECTS =  \
	newsreader_mswin_application.o \
	newsreader_mswin_app_win.o \
	newsreader_mswin_article_frame.o \
	newsreader_mswin_article_header.o \
	newsreader_mswin_headlines_frame.o \
	newsreader_mswin_rss_manage.o \
	newsreader_mswin_rss_article.o \
	newsreader_mswin_rss_feed.o \
	newsreader_mswin_rss_reader.o \
	newsreader_mswin_rss_util.o \
	newsreader_mswin_rss_writer.o \
	newsreader_mswin_db.o \
	newsreader_mswin_feed_download.o \
	newsreader_mswin_feed_parse.o

### Conditionally set variables: ###



### Targets: ###

all: bin/libgresources.a bin/newsreader_mswin

install: install_newsreader_mswin
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  app_icon.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/pixmaps/
	(cd ../source/rss_ui ; $(INSTALL) -m 644  app_icon.xpm $(DESTDIR)$(PREFIX)/share/pixmaps/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/applications/
	(cd ../desktop ; $(INSTALL) -m 644  newsreader.desktop $(DESTDIR)$(PREFIX)/share/applications/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/metainfo/
	(cd ../desktop ; $(INSTALL) -m 644  newsreader.appdata.xml $(DESTDIR)$(PREFIX)/share/metainfo/)
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/man/man7/
	(cd ../doc ; $(INSTALL) -m 644  newsreader.7 newsreader.7.gz $(DESTDIR)$(PREFIX)/share/man/man7/)

uninstall: uninstall_newsreader_mswin
	(cd $(DESTDIR)$(PREFIX)/share/icons/hicolor/48x48/apps/ ; rm -f app_icon.png)
	(cd $(DESTDIR)$(PREFIX)/share/pixmaps/ ; rm -f app_icon.xpm)
	(cd $(DESTDIR)$(PREFIX)/share/applications/ ; rm -f newsreader.desktop)
	(cd $(DESTDIR)$(PREFIX)/share/metainfo/ ; rm -f newsreader.appdata.xml)
	(cd $(DESTDIR)$(PREFIX)/share/man/man7/ ; rm -f newsreader.7 newsreader.7.gz)

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f bin/libgresources.a
	rm -f bin/newsreader_mswin

bin: 
	@mkdir -p bin

bin/libgresources.a: $(GRESOURCES_OBJECTS) bin ../source/rss_ui/app_style.css ../source/rss_ui/app_icon.png ../source/rss_ui/app_resources.xml
	rm -f $@
	$(AR) rcu $@ $(GRESOURCES_OBJECTS)
	$(RANLIB) $@

bin/newsreader_mswin: $(NEWSREADER_MSWIN_OBJECTS) bin bin/libgresources.a
	$(CXX) -o $@ $(NEWSREADER_MSWIN_OBJECTS)  gresources_app_resources.o -std=c++17 -pipe -O2 -flto `mingw64-pkg-config gtk+-3.0 --libs` `mingw64-pkg-config sqlite3 --libs` `mingw64-pkg-config libcurl --libs` `mingw64-pkg-config Qt5WebKit --libs` `mingw64-pkg-config libxml-2.0 --libs` `mingw64-pkg-config gthread-2.0 --libs` $(LDFLAGS)

install_newsreader_mswin: bin/newsreader_mswin
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/bin
	install -c bin/newsreader_mswin $(DESTDIR)$(PREFIX)/bin

uninstall_newsreader_mswin: 
	rm -f $(DESTDIR)$(PREFIX)/bin/newsreader_mswin

gresources_app_resources.o: ./../source/rss_ui/app_resources.c
	$(CC) -c -o $@ $(GRESOURCES_CFLAGS) $(CPPDEPS) $<

newsreader_mswin_application.o: ./../source/rss_ui/impl/application.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_app_win.o: ./../source/rss_ui/app_win/impl/app_win.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_article_frame.o: ./../source/rss_ui/app_win/impl/article_frame.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_article_header.o: ./../source/rss_ui/app_win/impl/article_header.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_headlines_frame.o: ./../source/rss_ui/app_win/impl/headlines_frame.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_rss_manage.o: ./../source/rss_ui/rss_manage/impl/rss_manage.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_rss_article.o: ./../source/rss_lib/rss/impl/rss_article.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_rss_feed.o: ./../source/rss_lib/rss/impl/rss_feed.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_rss_reader.o: ./../source/rss_lib/rss/impl/rss_reader.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_rss_util.o: ./../source/rss_lib/rss/impl/rss_util.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_rss_writer.o: ./../source/rss_lib/rss/impl/rss_writer.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_db.o: ./../source/rss_lib/db/impl/db.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_feed_download.o: ./../source/rss_lib/rss_download/impl/feed_download.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

newsreader_mswin_feed_parse.o: ./../source/rss_lib/rss_parse/impl/feed_parse.cpp
	$(CXX) -c -o $@ $(NEWSREADER_MSWIN_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean install_newsreader_mswin \
	uninstall_newsreader_mswin


# Dependencies tracking:
-include ./*.d
